cat << 'ENVEOF' > .env.example
# ==============================================================
# Variáveis de Ambiente - normajuridica.com
# ==============================================================

# 1. Inteligência Artificial e Plataforma
GEMINI_API_KEY=YOUR_GEMINI_API_KEY
APP_URL=https://normajuridica.com
NODE_ENV=development
DISABLE_HMR=true

# 2. Domínio e Roteamento
NEXT_PUBLIC_DOMAIN=https://normajuridica.com
VITE_SITE_URL=https://normajuridica.com
VITE_APP_URL=https://normajuridica.com
DOMAIN=normajuridica.com
API_KEY=YOUR_NEWS_API_KEY

# 3. Google AdSense
NEXT_PUBLIC_ADSENSE_ID=YOUR_ADSENSE_ID
NEXT_PUBLIC_ADSENSE_SLOT_HEADER=YOUR_ADSENSE_SLOT
NEXT_PUBLIC_ADSENSE_SLOT_SIDEBAR=YOUR_ADSENSE_SLOT
NEXT_PUBLIC_ADSENSE_SLOT_FOOTER=YOUR_ADSENSE_SLOT
GOOGLE_ADSENSE_CLIENT_ID=YOUR_ADSENSE_ID
GOOGLE_ADSENSE_SLOT_HEADER=YOUR_ADSENSE_SLOT
GOOGLE_ADSENSE_SLOT_SIDEBAR=YOUR_ADSENSE_SLOT
GOOGLE_ADSENSE_SLOT_SIDEBAR_BOTTOM=YOUR_ADSENSE_SLOT
GOOGLE_ADSENSE_SLOT_IN_ARTICLE=YOUR_ADSENSE_SLOT
GOOGLE_ADSENSE_SLOT_FOOTER=YOUR_ADSENSE_SLOT
VITE_GOOGLE_ADSENSE_CLIENT_ID=YOUR_ADSENSE_ID
VITE_GOOGLE_ADSENSE_SLOT_HEADER=YOUR_ADSENSE_SLOT
VITE_GOOGLE_ADSENSE_SLOT_SIDEBAR=YOUR_ADSENSE_SLOT
VITE_GOOGLE_ADSENSE_SLOT_SIDEBAR_BOTTOM=YOUR_ADSENSE_SLOT
VITE_GOOGLE_ADSENSE_SLOT_IN_ARTICLE=YOUR_ADSENSE_SLOT
VITE_GOOGLE_ADSENSE_SLOT_FOOTER=YOUR_ADSENSE_SLOT

# 4. Google Analytics
NEXT_PUBLIC_GA_MEASUREMENT_ID=YOUR_GA_MEASUREMENT_ID

# 5. Servidor SMTP
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=YOUR_SMTP_USER
SMTP_PASS=YOUR_SMTP_PASS
SMTP_FROM=YOUR_SMTP_FROM
SMTP_TO=YOUR_SMTP_TO
SMTP_FROM_EMAIL=YOUR_SMTP_FROM_EMAIL
SMTP_TO_EMAIL=YOUR_SMTP_TO_EMAIL

# 6. Firebase Realtime Database & Auth - Projeto 1 (Principal)
NEXT_PUBLIC_FIREBASE_API_KEY=YOUR_FIREBASE_API_KEY
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=YOUR_FIREBASE_AUTH_DOMAIN
NEXT_PUBLIC_FIREBASE_DATABASE_URL=YOUR_FIREBASE_DATABASE_URL
NEXT_PUBLIC_FIREBASE_PROJECT_ID=YOUR_FIREBASE_PROJECT_ID
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=YOUR_FIREBASE_STORAGE_BUCKET
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=YOUR_FIREBASE_MESSAGING_SENDER_ID
NEXT_PUBLIC_FIREBASE_APP_ID=YOUR_FIREBASE_APP_ID
VITE_FIREBASE_API_KEY=YOUR_FIREBASE_API_KEY
VITE_FIREBASE_AUTH_DOMAIN=YOUR_FIREBASE_AUTH_DOMAIN
VITE_FIREBASE_DATABASE_URL=YOUR_FIREBASE_DATABASE_URL
VITE_FIREBASE_PROJECT_ID=YOUR_FIREBASE_PROJECT_ID
VITE_FIREBASE_STORAGE_BUCKET=YOUR_FIREBASE_STORAGE_BUCKET
VITE_FIREBASE_MESSAGING_SENDER_ID=YOUR_FIREBASE_MESSAGING_SENDER_ID
VITE_FIREBASE_APP_ID=YOUR_FIREBASE_APP_ID

# 7. Firebase Realtime Database - Projeto 2 (Espelho / Rotação)
NEXT_PUBLIC_FIREBASE_2_API_KEY=YOUR_FIREBASE_2_API_KEY
NEXT_PUBLIC_FIREBASE_2_AUTH_DOMAIN=YOUR_FIREBASE_2_AUTH_DOMAIN
NEXT_PUBLIC_FIREBASE_2_DATABASE_URL=YOUR_FIREBASE_2_DATABASE_URL
NEXT_PUBLIC_FIREBASE_2_PROJECT_ID=YOUR_FIREBASE_2_PROJECT_ID
NEXT_PUBLIC_FIREBASE_2_STORAGE_BUCKET=YOUR_FIREBASE_2_STORAGE_BUCKET
NEXT_PUBLIC_FIREBASE_2_MESSAGING_SENDER_ID=YOUR_FIREBASE_2_MESSAGING_SENDER_ID
NEXT_PUBLIC_FIREBASE_2_APP_ID=YOUR_FIREBASE_2_APP_ID
VITE_FIREBASE_2_API_KEY=YOUR_FIREBASE_2_API_KEY
VITE_FIREBASE_2_AUTH_DOMAIN=YOUR_FIREBASE_2_AUTH_DOMAIN
VITE_FIREBASE_2_DATABASE_URL=YOUR_FIREBASE_2_DATABASE_URL
VITE_FIREBASE_2_PROJECT_ID=YOUR_FIREBASE_2_PROJECT_ID
VITE_FIREBASE_2_STORAGE_BUCKET=YOUR_FIREBASE_2_STORAGE_BUCKET
VITE_FIREBASE_2_MESSAGING_SENDER_ID=YOUR_FIREBASE_2_MESSAGING_SENDER_ID
VITE_FIREBASE_2_APP_ID=YOUR_FIREBASE_2_APP_ID

# 8. Administradores e Autenticação
ADMINISTRADORES=YOUR_ADMIN_EMAILS
VITE_ADMINISTRADORES=YOUR_ADMIN_EMAILS
ADMIN_PASSWORD=YOUR_ADMIN_PASSWORD
VITE_ADMIN_PASSWORD=YOUR_ADMIN_PASSWORD

# 9. Limites de Armazenamento e Tráfego com Sobrescrição Automática
LIMIT_STORAGE_BYTES=1932735283
LIMIT_TRAFFIC_BYTES=21474836480
SOBRECRICAO_STORAGE_LIMIT_MB=1900
SOBRECRICAO_TRAFFIC_LIMIT_GB=20
VITE_FIREBASE_STORAGE_LIMIT_BYTES=1932735283
VITE_FIREBASE_TRAFFIC_LIMIT_BYTES=21474836480

# 10. News & Media Upstream API
NEWS_API_BASE_URL=https://api-news-media.netlify.app
NEWS_API_KEY=YOUR_NEWS_API_KEY
NEWS_API_ENDPOINT_LIST_ALL_SOURCES=/api/news
NEWS_API_ENDPOINT_CATEGORY_BY_NAME=/api/news/category/{category}
NEWS_API_ENDPOINT_LIST_ALL_IMAGES=/api/images
NEWS_API_ENDPOINT_CATEGORIES=/api/categories
NEWS_API_ENDPOINT_TYPES=/api/types
NEWS_API_ENDPOINT_STATS=/api/stats
NEWS_API_ENDPOINT_OPENAPI_SPEC=/api/openapi.json

# (The rest of the non-sensitive configuration goes here)
ENVEOF
bash clean_env.sh
